### PR TITLE
Batch writes for StateStore

### PR DESCRIPTION
**Pull request by pflueras**
StateStore implementation for batch writes #23

### CODE REVIEW

**Review by VaughnVernon — APPROVED** [review]
@pflueras  👍

**Review by VaughnVernon — APPROVED** [review]
@pflueras 👍

**Review by VaughnVernon — APPROVED** [review]
@pflueras 👍

**Comment by jakzal** [comment]
@pflueras @VaughnVernon  I guess this section of docs needs updating now: https://docs.vlingo.io/vlingo-symbio/state-storage#configuring-and-starting-the-statestore

**Pull request merged**
